### PR TITLE
Feat: Plugins

### PR DESCRIPTION
**Pull request by showierdata9978**
- **Feat: PWA**
- **Make valid**
- **Use `portrait-primary` for orientation**
- **Fix(PWA): Caching and orientation**
- **"Roarer 2" → "Roarer"**
- **Feat: Plugins!**

### CODE REVIEW

**Comment by showierdata9978** [comment]
whar

**Comment by mybearworld** [comment]
All the commits on the `main` branch, which was the branch with the PWA stuff are here too lol

**Comment by mybearworld** [comment]
Putting everything in the global scope feels kind of hacky.
<sup>(I'm trying to make plugins be a thing done in the roarer slice as well, but it's acting a bit weird)</sup>

**Comment by showierdata9978** [comment]
> I feel like there's probably a better solution than putting everything in the global scope?

I mean I could do 

```
Roarer.
    plugins.
         loadPlugin
         flipPlugin
         data: RoarerData
    RoarerPlugin
```

**Comment by showierdata9978** [comment]
made a ts template for plugins
https://github.com/showierdata9978/roarer-plugin

**Comment by showierdata9978** [comment]
so many merge commits

**Pull request closed without merging**
