### PR TITLE
Use high quality Discord emojis

### PR DESCRIPTION
**Pull request by NotFenixio**

### CODE REVIEW

**Comment by mybearworld** [comment]
The image quality actually seems to become worse through this...

| Before | After |
|-|-|
| image | image

**Comment by NotFenixio** [comment]
| Before | After | 
|---|---|
|image|image|

**Comment by mybearworld** [comment]
That's zoomed in, though. At 100%, the improvement doesn't seem to be there

**Comment by NotFenixio** [comment]
Well, in the emoji picker, the difference is huge.

**Comment by NotFenixio** [comment]
this was a bad idea

**Pull request closed without merging**
