### PR TITLE
Feat: PWA

### PR DESCRIPTION
**Pull request by showierdata9978**

### CODE REVIEW

**Comment by mybearworld** [comment]
A problem with this is that it makes the site cache resources - so updates that are made won't get to people using the PWA very quickly.

**Comment by mybearworld** [comment]
Also, is the `orientation` part necessary? It causes my phone to ignore the fact that I have my orientation locked, and rotates it regardless.

**Comment by showierdata9978** [comment]
Idk why it rotates when locked

**Comment by showierdata9978** [comment]
try portrait-primary

**Comment by mybearworld** [comment]
> try portrait-primary

That seems to work

**Comment by showierdata9978** [comment]
LOL I also changed it per the commit message

**Comment by mybearworld** [comment]
This works, thank you!

**Pull request merged**
